application:
  name: hi1702

server:
  port: 8888
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/1702?useSSL=false&characterEncoding=utf8&useUnicode=true&useAffectedRows=true
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver


  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8

  jpa:
    hibernate:
      ddl-auto: update

# mail
  mail:
    host: smtp.mxhichina.com
    port: 25
    username: diyishuai2018@gmail.com
    password: hello1702
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true



# Logging
logging:
  config: classpath:logback-spring.xml
  path: logs